# generated by datamodel-codegen:
#   filename:  config.schema.yaml
#   timestamp: 2025-12-28T02:44:12+00:00
#   version:   0.49.0

from __future__ import annotations

from enum import IntEnum, StrEnum
from typing import Literal

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel


class Extent(BaseModel):
    """
    Geographic extent specification (direct coordinates or from KML file)
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["latlon"]
    """
    Direct lat/lon coordinate specification
    """
    min_lon: float = Field(..., ge=-180.0, le=180.0)
    """
    Western boundary longitude in degrees
    """
    min_lat: float = Field(..., ge=-90.0, le=90.0)
    """
    Southern boundary latitude in degrees
    """
    max_lon: float = Field(..., ge=-180.0, le=180.0)
    """
    Eastern boundary longitude in degrees
    """
    max_lat: float = Field(..., ge=-90.0, le=90.0)
    """
    Northern boundary latitude in degrees
    """


class Extent1(BaseModel):
    """
    Geographic extent specification (direct coordinates or from KML file)
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["file"]
    """
    KML file-based extent specification
    """
    file: str = Field(..., min_length=1)
    """
    Path to KML file (relative to config file or absolute)
    """
    padding: float | None = Field(default=0, ge=0.0)
    """
    Optional uniform padding in meters (applied to all sides)
    """


class AttributionMode(StrEnum):
    """
    How to display attribution - in description or as overlay
    """

    description = "description"
    overlay = "overlay"


class Outputs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["kmz"]
    """
    KMZ output format
    """
    path: str
    """
    Output file path
    """
    web_compatible: bool | None = False
    """
    Enable Google Earth Web compatibility (merges tiles, single zoom level)
    """
    attribution_mode: AttributionMode | None = AttributionMode.description
    """
    How to display attribution - in description or as overlay
    """
    merge_extent_kml: bool | None = False
    """
    Merge entire KML structure from extent file into generated KMZ. Only works when extent.type is 'file' and extent file is KML format.
    """


class ImageFormat(StrEnum):
    """
    Tile image format
    """

    png = "png"
    jpg = "jpg"


class ExportMode(StrEnum):
    """
    Export as single composite or separate files per layer
    """

    composite = "composite"
    separate = "separate"


class MetadataType(StrEnum):
    """
    Map type in metadata
    """

    baselayer = "baselayer"
    overlay = "overlay"


class Outputs1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["mbtiles"]
    """
    MBTiles output format
    """
    path: str
    """
    Output file path
    """
    image_format: ImageFormat | None = ImageFormat.png
    """
    Tile image format
    """
    jpeg_quality: int | None = Field(default=80, ge=1, le=100)
    """
    JPEG quality (1-100, only used with JPEG format)
    """
    export_mode: ExportMode | None = ExportMode.composite
    """
    Export as single composite or separate files per layer
    """
    metadata_name: str | None = None
    """
    Name in MBTiles metadata (overrides global name)
    """
    metadata_description: str | None = None
    """
    Description in MBTiles metadata (overrides global description)
    """
    metadata_type: MetadataType | None = MetadataType.overlay
    """
    Map type in metadata
    """


class Compression(StrEnum):
    """
    Compression method
    """

    lzw = "lzw"
    deflate = "deflate"
    jpeg = "jpeg"
    none = "none"


class TileSize(IntEnum):
    """
    Internal tile size in pixels (typically 256)
    """

    integer_128 = 128
    integer_256 = 256
    integer_512 = 512


class Outputs2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["geotiff"]
    """
    GeoTIFF output format
    """
    path: str
    """
    Output file path
    """
    compression: Compression | None = Compression.lzw
    """
    Compression method
    """
    jpeg_quality: int | None = Field(default=80, ge=1, le=100)
    """
    JPEG quality (1-100, only used with JPEG compression)
    """
    export_mode: ExportMode | None = ExportMode.composite
    """
    Export as single composite or separate files per layer
    """
    multi_zoom: bool | None = True
    """
    Include pyramids for all zoom levels (true) or single zoom (false)
    """
    tiled: bool | None = True
    """
    Use tiled format for optimized random access
    """
    tile_size: TileSize | None = TileSize.integer_256
    """
    Internal tile size in pixels (typically 256)
    """


class Layers(RootModel[str]):
    root: str = Field(..., min_length=1)
    """
    Layer name (must exist in built-in LAYERS or custom layer_sources). Uses default settings (opacity 100, blend_mode normal, etc.)
    """


class BlendMode(StrEnum):
    """
    Blend mode for compositing this layer with others
    """

    normal = "normal"
    multiply = "multiply"
    screen = "screen"
    overlay = "overlay"


class ExportMode2(StrEnum):
    """
    Whether to export as composite or separate layer
    """

    composite = "composite"
    separate = "separate"


class LodMode(StrEnum):
    """
    Level of detail mode - use all zoom levels or select specific ones
    """

    all_zooms = "all_zooms"
    select_zooms = "select_zooms"


class SelectedZoom(RootModel[int]):
    root: int = Field(..., ge=0, le=18)


class Layers1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., min_length=1)
    """
    Layer name (must exist in built-in LAYERS or custom layer_sources)
    """
    opacity: int | None = Field(default=100, ge=0, le=100)
    """
    Layer opacity (0=transparent, 100=opaque)
    """
    blend_mode: BlendMode | None = BlendMode.normal
    """
    Blend mode for compositing this layer with others
    """
    export_mode: ExportMode2 | None = ExportMode2.composite
    """
    Whether to export as composite or separate layer
    """
    enabled: bool | None = True
    """
    Whether this layer is active
    """
    lod_mode: LodMode | None = LodMode.all_zooms
    """
    Level of detail mode - use all zoom levels or select specific ones
    """
    selected_zooms: list[SelectedZoom] | None = Field(default=None, min_length=1)
    """
    Selected zoom levels (required when lod_mode=select_zooms). Each value must be 0-18.
    """


class Extension(StrEnum):
    """
    Tile image format
    """

    png = "png"
    jpg = "jpg"


class Category(StrEnum):
    """
    Layer category for organization
    """

    basemap = "basemap"
    photo = "photo"
    elevation = "elevation"
    landuse = "landuse"
    reference = "reference"
    disaster_eq = "disaster_eq"
    disaster_weather = "disaster_weather"
    disaster_volcano = "disaster_volcano"
    other = "other"


class LayerSources(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url_template: str
    """
    URL template with {z}, {x}, {y} placeholders for zoom, x, and y tile coordinates (any order)
    """
    extension: Extension
    """
    Tile image format
    """
    min_zoom: int = Field(..., ge=0, le=18)
    """
    Minimum zoom level available from this tile source
    """
    max_zoom: int = Field(..., ge=0, le=18)
    """
    Maximum zoom level available from this tile source
    """
    attribution: str = Field(..., min_length=1)
    """
    Attribution text (required for all custom sources)
    """
    display_name: str | None = None
    """
    Human-readable display name
    """
    description: str | None = None
    """
    Short description of the layer
    """
    japanese_name: str | None = None
    """
    Japanese name/title
    """
    full_description: str | None = None
    """
    Full/detailed description
    """
    info_url: AnyUrl | None = None
    """
    URL with more information about the layer
    """
    category: Category | None = Category.other
    """
    Layer category for organization
    """


class GoogleEarthTileGeneratorConfiguration(BaseModel):
    """
    Configuration schema for generating map tiles from WMTS sources for Google Earth, MBTiles, and GeoTIFF formats
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    extent: Extent | Extent1
    """
    Geographic extent specification (direct coordinates or from KML file)
    """
    min_zoom: int = Field(..., ge=2, le=18)
    """
    Minimum zoom level (2-18). Must be less than or equal to max_zoom.
    """
    max_zoom: int = Field(..., ge=2, le=18)
    """
    Maximum zoom level (2-18). Must be greater than or equal to min_zoom.
    """
    name: str | None = None
    """
    Optional name/title for the output tileset. Used in metadata for MBTiles and GeoTIFF outputs.
    """
    description: str | None = None
    """
    Optional description for the output tileset. Used in metadata for MBTiles and GeoTIFF outputs.
    """
    attribution: str | None = None
    """
    Optional attribution text for the tileset. Overrides default layer attribution if provided.
    """
    extract_extent_metadata: bool | None = False
    """
    Extract name and description metadata from KML extent file when extent.type is 'file'. Config-level name and description override extracted values.
    """
    outputs: list[Outputs | Outputs1 | Outputs2] = Field(..., min_length=1)
    """
    Output configurations. At least one output is required. Each output specifies a file format and path.
    """
    layers: list[Layers | Layers1] = Field(..., min_length=1)
    """
    Layer compositions. At least one layer is required. Supports simple string format or detailed object format.
    """
    layer_sources: dict[str, LayerSources] | None = None
    """
    Custom layer source definitions for WMTS/XYZ tile servers. Allows adding custom tile sources beyond the built-in Japan GSI layers.
    """
    include_timestamp: bool | None = True
    """
    CLI only: Include timestamp in generated output
    """
    enable_cache: bool | None = True
    """
    CLI only: Enable tile caching during generation
    """
